# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "aae890fd86a522d4bca428d93c339aa869db8f3e"

[[deps.Erebor]]
path = "."
uuid = "e895155b-0006-4513-b96e-06bf6b6a2ce2"
version = "1.0.0-DEV"
